create table TS_T_USUARIO(
ID_USUARIO INTEGER primary key,
EMAIL VARCHAR2(80),
SENHA VARCHAR2(150)
ADMINISTRADOR INTEGER,
PROFESSOR INTEGER,
ALUNO INTEGER,
);

CREATE TABLE TS_T_PESSOA(
ID_PESSOA number primary key,
NOME VARCHAR2(20),
SOBRENOME VARCHAR2(30),
ID_USUARIO integer
);